config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "avatars#index"
  get 'avatars', to: 'avatars#index'

  resources :avatars do
    resources :comments, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :catch_copy, presence: true
  validates :concept, presence: true
  validates :image, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :avatar

  validates :comment, presence: true
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :catch_copy, presence: true
  validates :concept, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true
  validates :profile, presence: true
  validates :occupation, presence: true
  validates :position, presence: true

  has_many :avatars
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :occupation, :position])
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_avatar, only: [:edit, :destroy]

  def index
    @avatars = Avatar.all
  end

  def new
    @avatar = Avatar.new
  end

  def create
    @avatar = Avatar.new(avatar_params)

    if @avatar.save
      redirect_to root_path
    else
     render :new
    end
  end

  def show
    @avatar = Avatar.find(params[:id])
    @comment = Comment.new
    @comments = @avatar.comments.includes(:user)
  end

  def edit
    @avatar = Avatar.find(params[:id])

    unless current_user == @avatar.user
      redirect_to action: :index
    end
  end

  def update
    @avatar = Avatar.find(params[:id])

    if @avatar.update(avatar_params)
      redirect_to avatar_path
    else
      render :edit
    end
  end

  def destroy
    avatar = Avatar.find(params[:id])
    avatar.destroy
    redirect_to root_path

    unless user_signed_in?
      redirect_to action: :root_path
    end
  end

  private
  def avatar_params
    params.require(:avatar).permit(:title, :catch_copy, :concept, :image).merge(user_id: current_user.id)
  end

  def set_avatar
    @avatar = Avatar.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to avatar_path(@comment.avatar)
    else
      @avatar = @comment.avatar
      @comments = @avatar.comments
      render 'avatars/show'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, avatar_id: params[:avatar_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @avatars = @user.avatars
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/avatars/_avatar.html.erb
<div class="card">
  <%= link_to image_tag(avatar.image, class: :card__img), avatar_path(avatar) %>
  <div class="card__body">
    <%= link_to avatar.title, avatar_path(avatar), class: :card__title%>
    <p class="card__summary">
      <%= avatar.catch_copy %>
    </p>
    <%= link_to "by #{avatar.user.name}", user_path(avatar.user.id), class: :card__user %>
  </div>
</div>

app/views/avatars/_form.html.erb
<%= form_with model: @avatar, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title, id:"avatar_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"avatar_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br /> 
    <%= f.text_area :concept, class: :form__text, id:"avatar_concept" %> 
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image, id:"avatar_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/avatars/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="avatar_path">投稿一覧へ戻る</a>
  </div>
</div>

app/views/avatars/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "avatars/form" %>
    </div>
  </div>
</div>

app/views/avatars/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">
        <%= link_to "#{current_user.name}さん、", user_path(current_user.id), class: :greeting__link%>
      <%=  "今日はどんなお仕事をしますか？" %>
      </div>
    <% end %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <%= render partial: "avatars/avatar", collection: @avatars %>
    </div>
  </div>
</main>

app/views/avatars/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "avatars/form" %>
    </div>
  </div>
</div>

app/views/avatars/show.html.erb
<main class="main">
  <div class="inner">
    <div class="avatar__wrapper">
      <p class="avatar__hedding">
        <%= @avatar.title %>
      </p>
      <%= link_to "by #{@avatar.user.name}", user_path(@avatar.user.id), class: :avatar__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @avatar.user_id %>
        <div class="avatar__manage">
          <%= link_to "編集する", edit_avatar_path(@avatar), method: :get, class: :avatar__btn %>
          <%= link_to "削除する", avatar_path(@avatar), method: :delete, class: :avatar__btn %>
        </div>
      <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="avatar__image">
        <%= image_tag(@avatar.image) %>
      </div>
      <div class="avatar__body">
        <div class="avatar__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @avatar.catch_copy %>
          </p>
        </div>
        <div class="avatar__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @avatar.concept %>
          </p>
        </div>
      </div>
      <div class="avatar__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
          <% if user_signed_in? %>
            <%= form_with(model: [@avatar, @comment], local: true) do |f|%>
              <div class="field">
                <%= f.label :comment, "コメント" %><br />
                <%= f.text_field :comment, id:"comment_content" %>
              </div>
              <div class="actions">
                <%= f.submit "送信する", class: :form__btn  %>
              </div>
            <% end %>
          <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
            <li class="comments_list">
              <% @comments.each do |comment| %>
                <p>
                  <%= comment.comment %>
                  <strong><%= link_to comment.user.name, user_path(comment.user.id), class: :comment_user %></strong>
                </p>
              <% end %>
            </li>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>らくらく職業体験</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("rakuraku.png", class: :logo), root_path %>
            <%= image_tag "logoimage.png", class: :logoimage %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %>
            <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to image_tag("logout.png", class: :semilogo), destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to image_tag("job.png", class: :semilogo), new_avatar_path, class: :nav__btn %>
            </div>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
            <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © JUNKO TAKANO All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with model: @prototype, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="prototype_path">投稿一覧へ戻る</a>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "prototypes/form" %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">
        <%=  "こんにちは、" %>
        <%= link_to "#{current_user.name}さん", user_path(current_user.id), class: :greeting__link%>
      </div>
    <% end %>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <%= render partial: "prototypes/prototype", collection: @prototypes %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "prototypes/form" %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.title %>
      </p>
      <%= link_to "by #{@prototype.user.name}", user_path(@prototype.user.id), class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @prototype.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path(@prototype), method: :get, class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <%= image_tag(@prototype.image) %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
          <% if user_signed_in? %>
            <%= form_with(model: [@prototype, @comment], local: true) do |f|%>
              <div class="field">
                <%= f.label :comment, "コメント" %><br />
                <%= f.text_field :comment, id:"comment_content" %>
              </div>
              <div class="actions">
                <%= f.submit "送信する", class: :form__btn  %>
              </div>
            <% end %>
          <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
            <li class="comments_list">
              <% @comments.each do |comment| %>
                <p>
                  <%= comment.comment %>
                  <strong><%= link_to comment.user.name, user_path(comment.user.id), class: :comment_user %></strong>
                </p>
              <% end %>
            </li>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @user.name %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= @avatar %>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <%= render partial: "avatars/avatar", collection: @avatars %>
      </div>
    </div>
  </div>
</div>